format = """
$python\
$directory\
( \\[$git_branch$git_status\\])\
[\\$ ]()
"""

#format = """
#$directory\
#[](fg:#DA627D bg:#86BBD8)\
#$git_branch\
#$git_status\
#[](fg:#86BBD8)\
#$cmd_duration\
#[ ]()
#"""

# $rust\
# [ ](fg:#86BBD8)\

command_timeout = 3000

# Disable the blank line at the start of the prompt
add_newline = false

[directory]
#style = "bg:#DA627D fg:#FFFFFF"
style = "bold fg:blue"
format = "[$path]($style)"
truncation_length = 1
truncate_to_repo = false
#truncation_symbol = "…/"
fish_style_pwd_dir_length = 2

[cmd_duration]
format = ' \(took [$duration]($style)\)'
show_milliseconds = true

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
#style = "bg:#86BBD8 fg:#FFFFFF"
format = '[$branch]($style)'

[git_status]
style = "fg:white"
format = '([/$staged$deleted$renamed$modified$ahead_behind]($style))'
deleted = "r"
staged = "a"
modified = "u"
renamed = "m"

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8 fg:#000000"
format = '[ $symbol ($version) ]($style)'
disabled = true

[python]
format = '[(\($virtualenv\) )]($style)'
