format = """
$directory\
[](fg:#DA627D bg:#86BBD8)\
$git_branch\
$git_status\
[ ](fg:#86BBD8)\
"""

# $rust\
# [ ](fg:#86BBD8)\

command_timeout = 3000

# Disable the blank line at the start of the prompt
add_newline = false

[directory]
style = "bg:#DA627D fg:#FFFFFF"
format = "[ $path ]($style)"
#truncation_length = 3
#truncation_symbol = "…/"
fish_style_pwd_dir_length = 2

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bg:#86BBD8 fg:#FFFFFF"
format = '[ $branch ]($style)'

[git_status]
style = "bg:#86BBD8"
format = '[$deleted$renamed$modified$staged$ahead_behind]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8 fg:#000000"
format = '[ $symbol ($version) ]($style)'
disabled = true
